import type { Metadata } from 'next'
import { Providers } from './providers'
import { Inter } from 'next/font/google'
import Menu from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Help the Helpless Charity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Menu />
          {children}
        </Providers>
      </body>
    </html>
  )
}
